executables:
  cellranger-rna: "/software/cellranger/6.0.0/bin/cellranger mkref"
genome: "/omics/groups/OE0538/internal/users/f844s/cellranger-ref/mm10/refdata-gex-mm10-2020-A/fasta/genome.fa"
annotation: "/omics/groups/OE0538/internal/users/f844s/cellranger-ref/mm10/refdata-gex-mm10-2020-A/genes/genes.gtf"
strains:
  - SPRET_EiJ
  - CAST_EiJ
additional_variant_bed_files:
  Mus_caroli: "/omics/groups/OE0538/internal/users/f844s/2022-bonemarrow/data/Caroli.snp.mm10.no_indels.no_chr.bed.gz"
per_strain_fasta: False
output_directory: "../2022-bonemarrow/data/masked_referencemasked_reference/"