executables:
  cellranger-rna: "/software/cellranger/6.0.0/bin/cellranger mkref"
genome: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/snp_masked_genome/input_files/cellranger-ref/mm10/refdata-gex-mm10-2020-A/fasta/genome.fa"
annotation: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/snp_masked_genome/input_files/cellranger-ref/mm10/refdata-gex-mm10-2020-A/genes/genes.gtf"
mgp_vcf_file: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/snp_masked_genome/input_files/mouse_dbsnp_keane2015/mgp.v5.merged.snps_all.dbSNP142.vcf.gz"
strains:
  - SPRET_EiJ
  - CAST_EiJ
additional_variant_bed_files:
  Mus_caroli: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/snp_masked_genome/input_files/m.caroli/Caroli.snp.mm10.no_indels.no_chr.bed.sorted.gz"
per_strain_fasta: False
cellranger_filter_gtf: False
make_cellranger_reference: False
mode: "incorporate_snvs"  # set "maskfasta" or "incorporate_snvs"
# maskfasta for allStrains = one masked reference genome -> scRNAseq data
# incorporate_snvs for four species-specific SNP-injected genomes -> MethylSeq data

output_directory: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/snp_masked_genome/incorporate_snvs/reference_snvs"
output_directory_mcaroli: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/snp_masked_genome/test_make"
cellranger_accepted_gene_transcript_types:
  - "protein_coding"
  - "lncRNA"
  - "antisense"
  - "IG_C_gene"
  - "IG_D_gene"
  - "IG_J_gene"
  - "IG_LV_gene"
  - "IG_V_gene"
  - "IG_V_pseudogene"
  - "IG_J_pseudogene"
  - "IG_C_pseudogene"
  - "TR_C_gene"
  - "TR_D_gene"
  - "TR_J_gene"
  - "TR_V_gene"
  - "TR_V_pseudogene"
  - "TR_J_pseudogene"
